version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql-database
      - mongo-database
    networks:
      - stock-exchange-network
      - exchange-messages_message_network

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql-database
      - mongo-database
    networks:
      - stock-exchange-network
      - exchange-messages_message_network

  mysql-database:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_streams
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql-database/data:/var/lib/mysql:rw
    networks:
      - stock-exchange-network

  mongo-database:
    image: mongo:latest
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - ./docker/mongo-database/data:/data/db:rw
    networks:
      - stock-exchange-network

networks:
  stock-exchange-network:
  exchange-messages_message_network:
    external: true